In [1]:
from generate_data import *

           date   weekday   ingredient  supplier_id  initial_quantity  \
0    2023-06-01  Thursday        Flour            0           29097.0
1    2023-06-01  Thursday  Brown Sugar            1           14628.0
2    2023-06-01  Thursday       Butter            2           14787.0
3    2023-06-01  Thursday         Eggs            4             551.1
4    2023-06-01  Thursday     Cinnamon            6            1327.0
..          ...       ...          ...          ...               ...
325  2023-06-30    Friday     Molasses            9            8511.0
326  2023-06-30    Friday         Salt           12             912.5
327  2023-06-30    Friday      Vanilla           14             576.5
328  2023-06-30    Friday         Milk           15            8709.0
329  2023-06-30    Friday        Honey           16            4451.0

     quantity_supplied  quantity_used  end_quantity  unit_cost
0              28958.0        28830.0       29225.0       0.50
1              14559.0        14415.0       14772.0       0.75
2              14738.0        14415.0       15110.0       8.00
3                227.1           96.1         682.1       0.20
4               1349.0          961.0        1715.0      10.00
..                 ...            ...           ...        ...
325             8466.0         8310.0        8667.0       2.00
326              644.5          415.5        1141.5       0.50
327              903.5          415.5        1064.5      15.00
328             8514.0         8310.0        8913.0       0.75
329             4591.0         4155.0        4887.0       5.00

[330 rows x 9 columns]

In [3]:

# Get supplier data first
supplier_data = generate_supplier_data()

# Generate ingredient supply data for June 2023
start_date = datetime(2023, 6, 1)
end_date = datetime(2023, 6, 30)
df_ingredient_supply_data = generate_ingredient_supply_data(
    start_date, end_date, supplier_data
)

In [4]:
df_ingredient_supply_data

,date,weekday,ingredient,supplier_id,initial_quantity,quantity_supplied,quantity_used,end_quantity,unit_cost
0,2023-06-01,Thursday,Flour,1,14014.0,14109.0,13860.0,14263.0,0.50
1,2023-06-01,Thursday,Brown Sugar,2,7193.0,7317.0,6930.0,7580.0,0.75
2,2023-06-01,Thursday,Butter,4,7242.0,7239.0,6930.0,7551.0,8.00
3,2023-06-01,Thursday,Eggs,6,315.2,231.2,46.2,500.2,0.20
4,2023-06-01,Thursday,Cinnamon,7,633.0,732.0,462.0,903.0,10.00
...,...,...,...,...,...,...,...,...,...
325,2023-06-30,Friday,Molasses,11,9033.0,8934.0,8600.0,9367.0,2.00
326,2023-06-30,Friday,Salt,12,873.0,762.0,430.0,1205.0,0.50
327,2023-06-30,Friday,Vanilla,14,672.0,673.0,430.0,915.0,15.00
328,2023-06-30,Friday,Milk,15,9020.0,8767.0,8600.0,9187.0,0.75
329,2023-06-30,Friday,Honey,16,4418.0,4653.0,4300.0,4771.0,5.00